// Code generated by protoc-gen-go-gin. DO NOT EDIT.
// versions:
// - protoc-gen-go-gin v1.0.0
// - protoc             v3.19.3
// source: proto/alltypetable.api.proto

package api

import (
	context "context"
	gin "github.com/gin-gonic/gin"
	binding "github.com/gin-gonic/gin/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
)

var allTypeTableServiceGin AllTypeTableServiceServerGin

// AllTypeTableServiceServer is the server API for AllTypeTableService service.
type AllTypeTableServiceServerGin interface {
	CreateAllTypeTable(context.Context, *AllTypeTable) (*AllTypeTable, error)
	DeleteAllTypeTable(context.Context, *AllTypeTableId) (*emptypb.Empty, error)
	UpdateAllTypeTable(context.Context, *UpdateAllTypeTableReq) (*AllTypeTable, error)
	GetAllTypeTable(context.Context, *AllTypeTableId) (*AllTypeTable, error)
	ListAllTypeTables(context.Context, *ListAllTypeTablesReq) (*ListAllTypeTablesResp, error)
}

func createAllTypeTableG(c *gin.Context) {
	a := &AllTypeTable{}
	err := c.BindWith(a, binding.Default(c.Request.Method, c.Request.Header.Get("Content-Type")))
	type Status struct {
		Code    int32       `json:"code"`
		Message string      `json:"message"`
		Data    interface{} `json:"data"`
	}
	status := &Status{}
	if err != nil {
		status.Code = http.StatusBadRequest
		status.Message = err.Error()
		c.JSON(http.StatusBadRequest, status)
		return
	}
	resp, err := allTypeTableServiceGin.CreateAllTypeTable(c, a)
	if err != nil {
		status.Code = http.StatusInternalServerError
		status.Message = err.Error()
		c.JSON(http.StatusInternalServerError, status)
		return
	}
	status.Data = resp
	c.JSON(http.StatusOK, status)
}
func deleteAllTypeTableG(c *gin.Context) {
	a := &AllTypeTableId{}
	err := c.BindWith(a, binding.Default(c.Request.Method, c.Request.Header.Get("Content-Type")))
	type Status struct {
		Code    int32       `json:"code"`
		Message string      `json:"message"`
		Data    interface{} `json:"data"`
	}
	status := &Status{}
	if err != nil {
		status.Code = http.StatusBadRequest
		status.Message = err.Error()
		c.JSON(http.StatusBadRequest, status)
		return
	}
	resp, err := allTypeTableServiceGin.DeleteAllTypeTable(c, a)
	if err != nil {
		status.Code = http.StatusInternalServerError
		status.Message = err.Error()
		c.JSON(http.StatusInternalServerError, status)
		return
	}
	status.Data = resp
	c.JSON(http.StatusOK, status)
}
func updateAllTypeTableG(c *gin.Context) {
	a := &UpdateAllTypeTableReq{}
	err := c.BindWith(a, binding.Default(c.Request.Method, c.Request.Header.Get("Content-Type")))
	type Status struct {
		Code    int32       `json:"code"`
		Message string      `json:"message"`
		Data    interface{} `json:"data"`
	}
	status := &Status{}
	if err != nil {
		status.Code = http.StatusBadRequest
		status.Message = err.Error()
		c.JSON(http.StatusBadRequest, status)
		return
	}
	resp, err := allTypeTableServiceGin.UpdateAllTypeTable(c, a)
	if err != nil {
		status.Code = http.StatusInternalServerError
		status.Message = err.Error()
		c.JSON(http.StatusInternalServerError, status)
		return
	}
	status.Data = resp
	c.JSON(http.StatusOK, status)
}
func getAllTypeTableG(c *gin.Context) {
	a := &AllTypeTableId{}
	err := c.BindWith(a, binding.Default(c.Request.Method, c.Request.Header.Get("Content-Type")))
	type Status struct {
		Code    int32       `json:"code"`
		Message string      `json:"message"`
		Data    interface{} `json:"data"`
	}
	status := &Status{}
	if err != nil {
		status.Code = http.StatusBadRequest
		status.Message = err.Error()
		c.JSON(http.StatusBadRequest, status)
		return
	}
	resp, err := allTypeTableServiceGin.GetAllTypeTable(c, a)
	if err != nil {
		status.Code = http.StatusInternalServerError
		status.Message = err.Error()
		c.JSON(http.StatusInternalServerError, status)
		return
	}
	status.Data = resp
	c.JSON(http.StatusOK, status)
}
func listAllTypeTablesG(c *gin.Context) {
	a := &ListAllTypeTablesReq{}
	err := c.BindWith(a, binding.Default(c.Request.Method, c.Request.Header.Get("Content-Type")))
	type Status struct {
		Code    int32       `json:"code"`
		Message string      `json:"message"`
		Data    interface{} `json:"data"`
	}
	status := &Status{}
	if err != nil {
		status.Code = http.StatusBadRequest
		status.Message = err.Error()
		c.JSON(http.StatusBadRequest, status)
		return
	}
	resp, err := allTypeTableServiceGin.ListAllTypeTables(c, a)
	if err != nil {
		status.Code = http.StatusInternalServerError
		status.Message = err.Error()
		c.JSON(http.StatusInternalServerError, status)
		return
	}
	status.Data = resp
	c.JSON(http.StatusOK, status)
}
func RegisterAllTypeTableServiceGin(e *gin.Engine, svr AllTypeTableServiceServerGin, middleware map[string][]gin.HandlerFunc) {
	allTypeTableServiceGin = svr
	e.POST("/example.AllTypeTableService/CreateAllTypeTable", append(middleware["/example.AllTypeTableService/CreateAllTypeTable"], createAllTypeTableG)...)
	e.POST("/example.AllTypeTableService/DeleteAllTypeTable", append(middleware["/example.AllTypeTableService/DeleteAllTypeTable"], deleteAllTypeTableG)...)
	e.POST("/example.AllTypeTableService/UpdateAllTypeTable", append(middleware["/example.AllTypeTableService/UpdateAllTypeTable"], updateAllTypeTableG)...)
	e.POST("/example.AllTypeTableService/GetAllTypeTable", append(middleware["/example.AllTypeTableService/GetAllTypeTable"], getAllTypeTableG)...)
	e.POST("/example.AllTypeTableService/ListAllTypeTables", append(middleware["/example.AllTypeTableService/ListAllTypeTables"], listAllTypeTablesG)...)
}
