// Code generated by bcurd. DO NOT EDIT.

package user

import (
	"time"
)

// User represents a row from 'user'.
type User struct {
	Id    int64     `json:"id"`    // id字段
	Name  string    `json:"name"`  // 名称
	Age   int64     `json:"age"`   // 年龄
	Ctime time.Time `json:"ctime"` // 创建时间
	Mtime time.Time `json:"mtime"` // 更新时间
}

const (
	// table tableName is user
	table = "user"
	//Id id字段
	Id = "id"
	//Name 名称
	Name = "name"
	//Age 年龄
	Age = "age"
	//Ctime 创建时间
	Ctime = "ctime"
	//Mtime 更新时间
	Mtime = "mtime"
)

// columns holds all SQL columns.
var columns = []string{
	Id,
	Name,
	Age,
	Ctime,
	Mtime,
}

// Columns returns table all columns field name slice
func Columns() []string {
	return columns
}
