// Code generated by bcurd. DO NOT EDIT.

package user

import (
	"time"
)

// User represents a row from 'user'.
type User struct {
	ID      int64     `json:"id"`      // id字段
	Name    string    `json:"name"`    // 名称
	Age     int64     `json:"age"`     // 年龄
	Ctime   time.Time `json:"ctime"`   // 创建时间
	Abit    []byte    `json:"abit"`    //
	Abinary []byte    `json:"abinary"` //
}

const (
	// table tableName is user
	table = "user"
	//ID id字段
	ID = "id"
	//Name 名称
	Name = "name"
	//Age 年龄
	Age = "age"
	//Ctime 创建时间
	Ctime = "ctime"
	//Abit
	Abit = "abit"
	//Abinary
	Abinary = "abinary"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	ID,
	Name,
	Age,
	Ctime,
	Abit,
	Abinary,
}

var dialect = "mysql"
