// Code generated by bcurd. DO NOT EDIT.

package user

import (
	"github.com/hongshengjie/xsql"
)

type UserWhere func(s *xsql.Selector)

// IDEQ  =
func IDEQ(arg uint32) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		s.Where(xsql.EQ(ID, arg))
	})
}

// IDNEQ <>
func IDNEQ(arg uint32) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		s.Where(xsql.NEQ(ID, arg))
	})
}

// IDLT <
func IDLT(arg uint32) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		s.Where(xsql.LT(ID, arg))
	})
}

// IDLET <=
func IDLTE(arg uint32) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		s.Where(xsql.LTE(ID, arg))
	})
}

// IDGT >
func IDGT(arg uint32) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		s.Where(xsql.GT(ID, arg))
	})
}

// IDGTE >=
func IDGTE(arg uint32) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		s.Where(xsql.GTE(ID, arg))
	})
}

// IDIn in(...)
func IDIn(args ...uint32) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		if len(args) == 0 {
			s.Where(xsql.False())
			return
		}
		v := make([]interface{}, len(args))
		for i := range v {
			v[i] = args[i]
		}
		s.Where(xsql.In(ID, v...))
	})
}

// IDNotIn not in(...)
func IDNotIn(args ...uint32) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		if len(args) == 0 {
			s.Where(xsql.False())
			return
		}
		v := make([]interface{}, len(args))
		for i := range v {
			v[i] = args[i]
		}
		s.Where(xsql.NotIn(ID, v...))
	})
}

// NameEQ  =
func NameEQ(arg string) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		s.Where(xsql.EQ(Name, arg))
	})
}

// NameNEQ <>
func NameNEQ(arg string) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		s.Where(xsql.NEQ(Name, arg))
	})
}

// NameLT <
func NameLT(arg string) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		s.Where(xsql.LT(Name, arg))
	})
}

// NameLET <=
func NameLTE(arg string) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		s.Where(xsql.LTE(Name, arg))
	})
}

// NameGT >
func NameGT(arg string) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		s.Where(xsql.GT(Name, arg))
	})
}

// NameGTE >=
func NameGTE(arg string) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		s.Where(xsql.GTE(Name, arg))
	})
}

// NameIn in(...)
func NameIn(args ...string) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		if len(args) == 0 {
			s.Where(xsql.False())
			return
		}
		v := make([]interface{}, len(args))
		for i := range v {
			v[i] = args[i]
		}
		s.Where(xsql.In(Name, v...))
	})
}

// NameNotIn not in(...)
func NameNotIn(args ...string) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		if len(args) == 0 {
			s.Where(xsql.False())
			return
		}
		v := make([]interface{}, len(args))
		for i := range v {
			v[i] = args[i]
		}
		s.Where(xsql.NotIn(Name, v...))
	})
}

// NameHasPrefix HasPrefix
func NameHasPrefix(arg string) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		s.Where(xsql.HasPrefix(Name, arg))
	})
}

// NameHasSuffix HasSuffix
func NameHasSuffix(arg string) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		s.Where(xsql.HasSuffix(Name, arg))
	})
}

// NameContains Contains
func NameContains(arg string) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		s.Where(xsql.Contains(Name, arg))
	})
}

// MtimeEQ  =
func MtimeEQ(arg string) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		s.Where(xsql.EQ(Mtime, arg))
	})
}

// MtimeNEQ <>
func MtimeNEQ(arg string) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		s.Where(xsql.NEQ(Mtime, arg))
	})
}

// MtimeLT <
func MtimeLT(arg string) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		s.Where(xsql.LT(Mtime, arg))
	})
}

// MtimeLET <=
func MtimeLTE(arg string) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		s.Where(xsql.LTE(Mtime, arg))
	})
}

// MtimeGT >
func MtimeGT(arg string) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		s.Where(xsql.GT(Mtime, arg))
	})
}

// MtimeGTE >=
func MtimeGTE(arg string) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		s.Where(xsql.GTE(Mtime, arg))
	})
}

// MtimeIn in(...)
func MtimeIn(args ...string) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		if len(args) == 0 {
			s.Where(xsql.False())
			return
		}
		v := make([]interface{}, len(args))
		for i := range v {
			v[i] = args[i]
		}
		s.Where(xsql.In(Mtime, v...))
	})
}

// MtimeNotIn not in(...)
func MtimeNotIn(args ...string) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		if len(args) == 0 {
			s.Where(xsql.False())
			return
		}
		v := make([]interface{}, len(args))
		for i := range v {
			v[i] = args[i]
		}
		s.Where(xsql.NotIn(Mtime, v...))
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...UserWhere) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...UserWhere) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p UserWhere) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		p(s.Not())
	})
}
