// Code generated by bcurd. DO NOT EDIT.

package user

import (
	"github.com/hongshengjie/xsql"
)

type UserWhere func(s *xsql.Selector)

// IDEQ  =
func IDEQ(arg uint32) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		s.Where(xsql.EQ(ID, arg))
	})
}

// IDNEQ <>
func IDNEQ(arg uint32) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		s.Where(xsql.NEQ(ID, arg))
	})
}

// IDLT <
func IDLT(arg uint32) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		s.Where(xsql.LT(ID, arg))
	})
}

// IDLET <=
func IDLTE(arg uint32) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		s.Where(xsql.LTE(ID, arg))
	})
}

// IDGT >
func IDGT(arg uint32) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		s.Where(xsql.GT(ID, arg))
	})
}

// IDGTE >=
func IDGTE(arg uint32) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		s.Where(xsql.GTE(ID, arg))
	})
}

// IDIn in(...)
func IDIn(args ...uint32) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		if len(args) == 0 {
			s.Where(xsql.False())
			return
		}
		v := make([]interface{}, len(args))
		for i := range v {
			v[i] = args[i]
		}
		s.Where(xsql.In(ID, v...))
	})
}

// IDNotIn not in(...)
func IDNotIn(args ...uint32) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		if len(args) == 0 {
			s.Where(xsql.False())
			return
		}
		v := make([]interface{}, len(args))
		for i := range v {
			v[i] = args[i]
		}
		s.Where(xsql.NotIn(ID, v...))
	})
}

// NameEQ  =
func NameEQ(arg string) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		s.Where(xsql.EQ(Name, arg))
	})
}

// NameNEQ <>
func NameNEQ(arg string) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		s.Where(xsql.NEQ(Name, arg))
	})
}

// NameLT <
func NameLT(arg string) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		s.Where(xsql.LT(Name, arg))
	})
}

// NameLET <=
func NameLTE(arg string) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		s.Where(xsql.LTE(Name, arg))
	})
}

// NameGT >
func NameGT(arg string) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		s.Where(xsql.GT(Name, arg))
	})
}

// NameGTE >=
func NameGTE(arg string) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		s.Where(xsql.GTE(Name, arg))
	})
}

// NameIn in(...)
func NameIn(args ...string) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		if len(args) == 0 {
			s.Where(xsql.False())
			return
		}
		v := make([]interface{}, len(args))
		for i := range v {
			v[i] = args[i]
		}
		s.Where(xsql.In(Name, v...))
	})
}

// NameNotIn not in(...)
func NameNotIn(args ...string) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		if len(args) == 0 {
			s.Where(xsql.False())
			return
		}
		v := make([]interface{}, len(args))
		for i := range v {
			v[i] = args[i]
		}
		s.Where(xsql.NotIn(Name, v...))
	})
}

// NameHasPrefix HasPrefix
func NameHasPrefix(arg string) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		s.Where(xsql.HasPrefix(Name, arg))
	})
}

// NameHasSuffix HasSuffix
func NameHasSuffix(arg string) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		s.Where(xsql.HasSuffix(Name, arg))
	})
}

// NameContains Contains
func NameContains(arg string) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		s.Where(xsql.Contains(Name, arg))
	})
}

// AgeEQ  =
func AgeEQ(arg int32) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		s.Where(xsql.EQ(Age, arg))
	})
}

// AgeNEQ <>
func AgeNEQ(arg int32) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		s.Where(xsql.NEQ(Age, arg))
	})
}

// AgeLT <
func AgeLT(arg int32) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		s.Where(xsql.LT(Age, arg))
	})
}

// AgeLET <=
func AgeLTE(arg int32) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		s.Where(xsql.LTE(Age, arg))
	})
}

// AgeGT >
func AgeGT(arg int32) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		s.Where(xsql.GT(Age, arg))
	})
}

// AgeGTE >=
func AgeGTE(arg int32) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		s.Where(xsql.GTE(Age, arg))
	})
}

// AgeIn in(...)
func AgeIn(args ...int32) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		if len(args) == 0 {
			s.Where(xsql.False())
			return
		}
		v := make([]interface{}, len(args))
		for i := range v {
			v[i] = args[i]
		}
		s.Where(xsql.In(Age, v...))
	})
}

// AgeNotIn not in(...)
func AgeNotIn(args ...int32) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		if len(args) == 0 {
			s.Where(xsql.False())
			return
		}
		v := make([]interface{}, len(args))
		for i := range v {
			v[i] = args[i]
		}
		s.Where(xsql.NotIn(Age, v...))
	})
}

// CtimeEQ  =
func CtimeEQ(arg string) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		s.Where(xsql.EQ(Ctime, arg))
	})
}

// CtimeNEQ <>
func CtimeNEQ(arg string) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		s.Where(xsql.NEQ(Ctime, arg))
	})
}

// CtimeLT <
func CtimeLT(arg string) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		s.Where(xsql.LT(Ctime, arg))
	})
}

// CtimeLET <=
func CtimeLTE(arg string) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		s.Where(xsql.LTE(Ctime, arg))
	})
}

// CtimeGT >
func CtimeGT(arg string) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		s.Where(xsql.GT(Ctime, arg))
	})
}

// CtimeGTE >=
func CtimeGTE(arg string) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		s.Where(xsql.GTE(Ctime, arg))
	})
}

// CtimeIn in(...)
func CtimeIn(args ...string) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		if len(args) == 0 {
			s.Where(xsql.False())
			return
		}
		v := make([]interface{}, len(args))
		for i := range v {
			v[i] = args[i]
		}
		s.Where(xsql.In(Ctime, v...))
	})
}

// CtimeNotIn not in(...)
func CtimeNotIn(args ...string) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		if len(args) == 0 {
			s.Where(xsql.False())
			return
		}
		v := make([]interface{}, len(args))
		for i := range v {
			v[i] = args[i]
		}
		s.Where(xsql.NotIn(Ctime, v...))
	})
}

// AbitEQ  =
func AbitEQ(arg int64) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		s.Where(xsql.EQ(Abit, arg))
	})
}

// AbitNEQ <>
func AbitNEQ(arg int64) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		s.Where(xsql.NEQ(Abit, arg))
	})
}

// AbitLT <
func AbitLT(arg int64) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		s.Where(xsql.LT(Abit, arg))
	})
}

// AbitLET <=
func AbitLTE(arg int64) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		s.Where(xsql.LTE(Abit, arg))
	})
}

// AbitGT >
func AbitGT(arg int64) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		s.Where(xsql.GT(Abit, arg))
	})
}

// AbitGTE >=
func AbitGTE(arg int64) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		s.Where(xsql.GTE(Abit, arg))
	})
}

// AbitIn in(...)
func AbitIn(args ...int64) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		if len(args) == 0 {
			s.Where(xsql.False())
			return
		}
		v := make([]interface{}, len(args))
		for i := range v {
			v[i] = args[i]
		}
		s.Where(xsql.In(Abit, v...))
	})
}

// AbitNotIn not in(...)
func AbitNotIn(args ...int64) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		if len(args) == 0 {
			s.Where(xsql.False())
			return
		}
		v := make([]interface{}, len(args))
		for i := range v {
			v[i] = args[i]
		}
		s.Where(xsql.NotIn(Abit, v...))
	})
}

// AbinaryEQ  =
func AbinaryEQ(arg []byte) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		s.Where(xsql.EQ(Abinary, arg))
	})
}

// AbinaryNEQ <>
func AbinaryNEQ(arg []byte) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		s.Where(xsql.NEQ(Abinary, arg))
	})
}

// AbinaryLT <
func AbinaryLT(arg []byte) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		s.Where(xsql.LT(Abinary, arg))
	})
}

// AbinaryLET <=
func AbinaryLTE(arg []byte) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		s.Where(xsql.LTE(Abinary, arg))
	})
}

// AbinaryGT >
func AbinaryGT(arg []byte) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		s.Where(xsql.GT(Abinary, arg))
	})
}

// AbinaryGTE >=
func AbinaryGTE(arg []byte) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		s.Where(xsql.GTE(Abinary, arg))
	})
}

// AbinaryIn in(...)
func AbinaryIn(args ...[]byte) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		if len(args) == 0 {
			s.Where(xsql.False())
			return
		}
		v := make([]interface{}, len(args))
		for i := range v {
			v[i] = args[i]
		}
		s.Where(xsql.In(Abinary, v...))
	})
}

// AbinaryNotIn not in(...)
func AbinaryNotIn(args ...[]byte) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		if len(args) == 0 {
			s.Where(xsql.False())
			return
		}
		v := make([]interface{}, len(args))
		for i := range v {
			v[i] = args[i]
		}
		s.Where(xsql.NotIn(Abinary, v...))
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...UserWhere) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...UserWhere) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p UserWhere) UserWhere {
	return UserWhere(func(s *xsql.Selector) {
		p(s.Not())
	})
}
